# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - dev
pr:
  branches:
    include:
    - dev

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"

pool:
  vmImage: $(imageName)

steps:

- script: echo WORKFLOW_USERNAME=$ENV_WORKFLOW_USERNAME
  displayName: 'Echo environment'
  env:
    ENV_WORKFLOW_USERNAME: $(WORKFLOW_USERNAME)
