# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - dev

pr:
  branches:
    include:
    - dev

strategy:
  matrix:
    linux:
      imageName: "ubuntu-16.04"
#    mac:
#      imageName: "macos-10.14"
#    windows:
#      imageName: "vs2017-win2016"
#  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:

- script: echo WORKFLOW_USERNAME=$ENV_WORKFLOW_USERNAME
  displayName: 'Echo environment'
  env:
    ENV_WORKFLOW_USERNAME: $(WORKFLOW_USERNAME)

- script: curl -v --user $(WORKFLOW_USERNAME):$(WORKFLOW_PASSWORD) -O $(MAYA_USD_JSON_URL)
  displayName: 'Download a file'

- script: cat Autodesk_Maya_2019_2_Update_Short-Long-descriptions.json
  displayName: 'Cat downloaded file'

- script: echo WORKFLOW_USERNAME=$ENV_WORKFLOW_USERNAME
  displayName: 'Change workflow'
  env:
    ENV_WORKFLOW_USERNAME: $(WORKFLOW_USERNAME)
