#!/bin/bash

export AL_USDMAYA_LOCATION=$1
export USD_LIBRARY_PATH=$2
export TEST_DIR=$3
export PXR_USDMAYA_LOCATION=$4
export MAYA_PLUG_IN_PATH=$AL_USDMAYA_LOCATION/plugin:$PXR_USDMAYA_LOCATION/maya/plugin:$MAYA_PLUG_IN_PATH
export LD_LIBRARY_PATH=$AL_USDMAYA_LOCATION/lib:$USD_LIBRARY_PATH:$LD_LIBRARY_PATH
export PYTHONPATH=$AL_USDMAYA_LOCATION/lib/python:$PXR_USDMAYA_LOCATION/lib/python:$USD_LIBRARY_PATH/python:$TEST_DIR:$PYTHONPATH
export PXR_PLUGINPATH_NAME=$AL_USDMAYA_LOCATION/plugin:$PXR_PLUGINPATH_NAME
export PATH=$MAYA_LOCATION/bin:$PATH

maya -batch -command "python(\"execfile(\\\"$TEST_DIR/testPxrTranslators.py\\\")\")"

exit $?
