#!/bin/bash

export AL_MAYAUTILS_TEST_MAYAPLUGIN_PATH=$1
export LD_LIBRARY_PATH=$MAYA_LOCATION/lib:$LD_LIBRARY_PATH
export PATH=$MAYA_LOCATION/bin:$PATH
export MAYA_PLUG_IN_PATH=$AL_MAYAUTILS_TEST_MAYAPLUGIN_PATH:$MAYA_PLUG_IN_PATH

maya -batch -script "$2/run_tests.mel"
