global proc hydraViewportOverrideOptionBox() {
    string $windowName = "hydraViewportOverrideOptionsWindow";
    if (`window -exists $windowName`) {
        showWindow $windowName;
        return;
    }

    createNode -name "MtohRenderGlobals" -shared "MtohRenderGlobals";

    window -menuBar true -title "Maya to Hydra Options" -retain $windowName;
    createAETabInWindow("MtohRenderGlobals", $windowName);
}
