#ifndef __HDMAYA_ADAPTER_DEBUG_CODES_H__
#define __HDMAYA_ADAPTER_DEBUG_CODES_H__

#include <pxr/pxr.h>
#include <pxr/base/tf/debug.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
    HDMAYA_ADAPTER_MESH_PLUG_DIRTY,
    HDMAYA_ADAPTER_MESH_UNHANDLED_PLUG_DIRTY
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // __HDMAYA_ADAPTER_DEBUG_CODES_H__
