//Maya ASCII 2024 scene
//Name: multi_uv_simple.ma
//Last modified: Fri, Oct 13, 2023 12:08:36 PM
//Codeset: UTF-8
requires maya "2022";
currentUnit -l centimeter -a degree -t film;
fileInfo "UUID" "3F334087-294B-5BCC-7397-6693C798D48A";
createNode transform -n "multi_uv";
	rename -uid "E2516280-9148-8B58-2147-AEA6517D3D18";
createNode transform -n "mesh_template24x" -p "multi_uv";
	rename -uid "FEBE8ECB-0245-3DFC-A3B0-2D9B1ADDA032";
	setAttr ".hdl" -type "double3" 141.6311137495947 0 -2 ;
	setAttr ".dh" yes;
createNode mesh -n "mesh_template24xShape" -p "mesh_template24x";
	rename -uid "91F7C3AB-4141-6C61-E3FA-AD917BF85BAA";
	setAttr -k off ".v";
	setAttr ".vir" yes;
	setAttr ".vif" yes;
	setAttr ".pv" -type "double2" 0.5 0.5 ;
	setAttr -s 2 ".uvst";
	setAttr ".uvst[0].uvsn" -type "string" "map1";
	setAttr -s 4 ".uvst[0].uvsp[0:3]" -type "float2" 0 0 1 0 0 1 1 1;
	setAttr ".uvst[1].uvsn" -type "string" "map2";
	setAttr -s 4 ".uvst[1].uvsp[0:3]" -type "float2" -0.91421354 0.5 0.5
		 -0.91421354 1.91421354 0.5 0.5 1.91421354;
	setAttr ".cuvs" -type "string" "map2";
	setAttr ".dcol" yes;
	setAttr ".dcc" -type "string" "Ambient+Diffuse";
	setAttr ".covm[0]"  0 1 1;
	setAttr ".cdvm[0]"  0 1 1;
	setAttr -s 4 ".pt[0:3]" -type "float3"  10.000008 -17.346029 3.5527137e-15 
		10.000008 -17.346029 3.5527137e-15 10.000008 -17.346029 3.5527137e-15 10.000008 -17.346029 
		3.5527137e-15;
	setAttr -s 4 ".vt[0:3]"  -15 12.34603024 -3.5527137e-15 -5 12.34603024 -3.5527137e-15
		 -15 22.34603119 -3.5527137e-15 -5 22.34603119 -3.5527137e-15;
	setAttr -s 4 ".ed[0:3]"  0 1 0 0 2 0 1 3 0 2 3 0;
	setAttr -ch 4 ".fc[0]" -type "polyFaces" 
		f 4 0 2 -4 -2
		mu 0 4 0 1 3 2
		mu 1 4 0 1 2 3;
	setAttr ".cd" -type "dataPolyComponent" Index_Data Edge 0 ;
	setAttr ".cvd" -type "dataPolyComponent" Index_Data Vertex 0 ;
	setAttr -s 2 ".pd";
	setAttr ".pd[0]" -type "dataPolyComponent" Index_Data UV 0 ;
	setAttr ".pd[1]" -type "dataPolyComponent" Index_Data UV 0 ;
	setAttr ".hfd" -type "dataPolyComponent" Index_Data Face 0 ;
	setAttr ".dmb" yes;
	setAttr ".de" 1;
createNode materialInfo -n "materialInfo40";
	rename -uid "AAAAE064-2649-F2C2-1AE4-2DB36D0F509A";
createNode shadingEngine -n "multi_uv_set_matSG";
	rename -uid "8D0A2ED7-214A-C2A9-7BC1-C1A4786FD2D6";
	setAttr ".ro" yes;
createNode usdPreviewSurface -n "multi_uv_set_mat";
	rename -uid "53E241DE-9542-2711-69AC-9E90C73F916C";
	setAttr ".rgh" 0;
createNode file -n "texcoord_checker_up_bc";
	rename -uid "6E459667-6B4F-D407-448C-02867411F938";
	setAttr ".ftn" -type "string" "/Users/dhruvgovil/Projects/maya-usd/test/lib/usd/translators/UsdExportUVSetMappingsTest/label_bc.png";
	setAttr ".ifr" yes;
createNode place2dTexture -n "place2dTexture25";
	rename -uid "0FB663F3-F04B-B1EF-74EB-F9A1FB66CA32";
createNode uvChooser -n "uvChooser1";
	rename -uid "DCCE2F32-564A-9E87-782A-27A70FA55A66";
createNode file -n "uv_grid_ao";
	rename -uid "4232A0AC-DA44-6D89-C881-7384AA789D0C";
	setAttr ".ftn" -type "string" "/Users/dhruvgovil/Projects/maya-usd/test/lib/usd/translators/UsdExportUVSetMappingsTest/label_ao.png";
	setAttr ".ifr" yes;
createNode place2dTexture -n "place2dTexture26";
	rename -uid "BF0B9EF2-414D-B935-C98B-88ABFAA8BF80";
createNode file -n "uv_grid_ao_opacity";
	rename -uid "264ED64E-484B-02CD-2132-2BB8768640DE";
	setAttr ".ftn" -type "string" "/Users/dhruvgovil/Projects/maya-usd/test/lib/usd/translators/UsdExportUVSetMappingsTest/label_o.png";
	setAttr ".ifr" yes;
createNode place2dTexture -n "place2dTexture41";
	rename -uid "B5D3DC31-3547-7F99-474C-8985FB4AC028";
createNode lightLinker -s -n "lightLinker1";
	rename -uid "1B557CD5-FE42-EA2B-84E8-EE9E30944CDE";
	setAttr -s 4 ".lnk";
	setAttr -s 4 ".slnk";
select -ne :time1;
	setAttr -av -k on ".cch";
	setAttr -av -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".o" 69;
	setAttr -av -k on ".unw" 69;
	setAttr -av -k on ".etw";
	setAttr -av -k on ".tps";
	setAttr -av -k on ".tms";
select -ne :hardwareRenderingGlobals;
	setAttr -av -k on ".ihi";
	setAttr ".otfna" -type "stringArray" 22 "NURBS Curves" "NURBS Surfaces" "Polygons" "Subdiv Surface" "Particles" "Particle Instance" "Fluids" "Strokes" "Image Planes" "UI" "Lights" "Cameras" "Locators" "Joints" "IK Handles" "Deformers" "Motion Trails" "Components" "Hair Systems" "Follicles" "Misc. UI" "Ornaments"  ;
	setAttr ".otfva" -type "Int32Array" 22 0 1 1 1 1 1
		 1 1 1 0 0 0 0 0 0 0 0 0
		 0 0 0 0 ;
	setAttr -k on ".hwi";
	setAttr -av ".ta";
	setAttr -av ".tq";
	setAttr ".etmr" no;
	setAttr ".tmr" 4096;
	setAttr -av ".aoam";
	setAttr -av ".aora";
	setAttr -av ".hfd";
	setAttr -av ".hfe";
	setAttr -av ".hfcr";
	setAttr -av ".hfcg";
	setAttr -av ".hfcb";
	setAttr -av ".hfa";
	setAttr -av ".mbe";
	setAttr -av -k on ".mbsof";
	setAttr -k on ".blen";
	setAttr -k on ".blat";
	setAttr ".dli" 1;
	setAttr ".fprt" yes;
	setAttr ".rtfm" 1;
select -ne :renderPartition;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 4 ".st";
	setAttr -cb on ".an";
	setAttr -cb on ".pt";
select -ne :renderGlobalsList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
select -ne :defaultShaderList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 7 ".s";
select -ne :postProcessList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 2 ".p";
select -ne :defaultRenderUtilityList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 3 ".u";
select -ne :defaultRenderingList1;
	setAttr -k on ".ihi";
select -ne :defaultTextureList1;
	setAttr -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -s 3 ".tx";
select -ne :standardSurface1;
	setAttr ".b" 0.80000001192092896;
	setAttr ".bc" -type "float3" 1 1 1 ;
	setAttr ".s" 0.20000000298023224;
	setAttr ".sr" 0.40000000596046448;
select -ne :initialShadingGroup;
	setAttr -av -k on ".cch";
	setAttr -k on ".fzn";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".bbx";
	setAttr -k on ".vwm";
	setAttr -k on ".tpv";
	setAttr -k on ".uit";
	setAttr -k on ".mwc";
	setAttr -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
select -ne :initialParticleSE;
	setAttr -av -k on ".cch";
	setAttr -cb on ".ihi";
	setAttr -av -k on ".nds";
	setAttr -cb on ".bnm";
	setAttr -k on ".mwc";
	setAttr -cb on ".an";
	setAttr -cb on ".il";
	setAttr -cb on ".vo";
	setAttr -cb on ".eo";
	setAttr -cb on ".fo";
	setAttr -cb on ".epo";
	setAttr -k on ".ro" yes;
connectAttr "multi_uv_set_matSG.msg" "materialInfo40.sg";
connectAttr "multi_uv_set_mat.msg" "materialInfo40.m";
connectAttr "texcoord_checker_up_bc.msg" "materialInfo40.t" -na;
connectAttr "multi_uv_set_mat.oc" "multi_uv_set_matSG.ss";
connectAttr "mesh_template24xShape.iog" "multi_uv_set_matSG.dsm" -na;
connectAttr "texcoord_checker_up_bc.oc" "multi_uv_set_mat.dc";
connectAttr "uv_grid_ao.ocr" "multi_uv_set_mat.ocl";
connectAttr "uv_grid_ao_opacity.ocr" "multi_uv_set_mat.opc";
connectAttr ":defaultColorMgtGlobals.cme" "texcoord_checker_up_bc.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "texcoord_checker_up_bc.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "texcoord_checker_up_bc.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "texcoord_checker_up_bc.ws";
connectAttr "place2dTexture25.c" "texcoord_checker_up_bc.c";
connectAttr "place2dTexture25.tf" "texcoord_checker_up_bc.tf";
connectAttr "place2dTexture25.rf" "texcoord_checker_up_bc.rf";
connectAttr "place2dTexture25.mu" "texcoord_checker_up_bc.mu";
connectAttr "place2dTexture25.mv" "texcoord_checker_up_bc.mv";
connectAttr "place2dTexture25.s" "texcoord_checker_up_bc.s";
connectAttr "place2dTexture25.wu" "texcoord_checker_up_bc.wu";
connectAttr "place2dTexture25.wv" "texcoord_checker_up_bc.wv";
connectAttr "place2dTexture25.re" "texcoord_checker_up_bc.re";
connectAttr "place2dTexture25.of" "texcoord_checker_up_bc.of";
connectAttr "place2dTexture25.r" "texcoord_checker_up_bc.ro";
connectAttr "place2dTexture25.n" "texcoord_checker_up_bc.n";
connectAttr "place2dTexture25.vt1" "texcoord_checker_up_bc.vt1";
connectAttr "place2dTexture25.vt2" "texcoord_checker_up_bc.vt2";
connectAttr "place2dTexture25.vt3" "texcoord_checker_up_bc.vt3";
connectAttr "place2dTexture25.vc1" "texcoord_checker_up_bc.vc1";
connectAttr "place2dTexture25.o" "texcoord_checker_up_bc.uv";
connectAttr "place2dTexture25.ofs" "texcoord_checker_up_bc.fs";
connectAttr "uvChooser1.ov1" "place2dTexture25.vt1";
connectAttr "uvChooser1.ov2" "place2dTexture25.vt2";
connectAttr "uvChooser1.ov3" "place2dTexture25.vt3";
connectAttr "uvChooser1.oc1" "place2dTexture25.vc1";
connectAttr "uvChooser1.ouv" "place2dTexture25.uv";
connectAttr "mesh_template24xShape.uvst[1].uvsn" "uvChooser1.uvs[1]";
connectAttr ":defaultColorMgtGlobals.cme" "uv_grid_ao.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "uv_grid_ao.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "uv_grid_ao.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "uv_grid_ao.ws";
connectAttr "place2dTexture26.c" "uv_grid_ao.c";
connectAttr "place2dTexture26.tf" "uv_grid_ao.tf";
connectAttr "place2dTexture26.rf" "uv_grid_ao.rf";
connectAttr "place2dTexture26.mu" "uv_grid_ao.mu";
connectAttr "place2dTexture26.mv" "uv_grid_ao.mv";
connectAttr "place2dTexture26.s" "uv_grid_ao.s";
connectAttr "place2dTexture26.wu" "uv_grid_ao.wu";
connectAttr "place2dTexture26.wv" "uv_grid_ao.wv";
connectAttr "place2dTexture26.re" "uv_grid_ao.re";
connectAttr "place2dTexture26.of" "uv_grid_ao.of";
connectAttr "place2dTexture26.r" "uv_grid_ao.ro";
connectAttr "place2dTexture26.n" "uv_grid_ao.n";
connectAttr "place2dTexture26.vt1" "uv_grid_ao.vt1";
connectAttr "place2dTexture26.vt2" "uv_grid_ao.vt2";
connectAttr "place2dTexture26.vt3" "uv_grid_ao.vt3";
connectAttr "place2dTexture26.vc1" "uv_grid_ao.vc1";
connectAttr "place2dTexture26.o" "uv_grid_ao.uv";
connectAttr "place2dTexture26.ofs" "uv_grid_ao.fs";
connectAttr ":defaultColorMgtGlobals.cme" "uv_grid_ao_opacity.cme";
connectAttr ":defaultColorMgtGlobals.cfe" "uv_grid_ao_opacity.cmcf";
connectAttr ":defaultColorMgtGlobals.cfp" "uv_grid_ao_opacity.cmcp";
connectAttr ":defaultColorMgtGlobals.wsn" "uv_grid_ao_opacity.ws";
connectAttr "place2dTexture41.c" "uv_grid_ao_opacity.c";
connectAttr "place2dTexture41.tf" "uv_grid_ao_opacity.tf";
connectAttr "place2dTexture41.rf" "uv_grid_ao_opacity.rf";
connectAttr "place2dTexture41.mu" "uv_grid_ao_opacity.mu";
connectAttr "place2dTexture41.mv" "uv_grid_ao_opacity.mv";
connectAttr "place2dTexture41.s" "uv_grid_ao_opacity.s";
connectAttr "place2dTexture41.wu" "uv_grid_ao_opacity.wu";
connectAttr "place2dTexture41.wv" "uv_grid_ao_opacity.wv";
connectAttr "place2dTexture41.re" "uv_grid_ao_opacity.re";
connectAttr "place2dTexture41.of" "uv_grid_ao_opacity.of";
connectAttr "place2dTexture41.r" "uv_grid_ao_opacity.ro";
connectAttr "place2dTexture41.n" "uv_grid_ao_opacity.n";
connectAttr "place2dTexture41.vt1" "uv_grid_ao_opacity.vt1";
connectAttr "place2dTexture41.vt2" "uv_grid_ao_opacity.vt2";
connectAttr "place2dTexture41.vt3" "uv_grid_ao_opacity.vt3";
connectAttr "place2dTexture41.vc1" "uv_grid_ao_opacity.vc1";
connectAttr "place2dTexture41.o" "uv_grid_ao_opacity.uv";
connectAttr "place2dTexture41.ofs" "uv_grid_ao_opacity.fs";
relationship "link" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "link" ":lightLinker1" "multi_uv_set_matSG.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialShadingGroup.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" ":initialParticleSE.message" ":defaultLightSet.message";
relationship "shadowLink" ":lightLinker1" "multi_uv_set_matSG.message" ":defaultLightSet.message";
connectAttr "multi_uv_set_matSG.pa" ":renderPartition.st" -na;
connectAttr "multi_uv_set_mat.msg" ":defaultShaderList1.s" -na;
connectAttr "place2dTexture25.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "place2dTexture26.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "place2dTexture41.msg" ":defaultRenderUtilityList1.u" -na;
connectAttr "texcoord_checker_up_bc.msg" ":defaultTextureList1.tx" -na;
connectAttr "uv_grid_ao.msg" ":defaultTextureList1.tx" -na;
connectAttr "uv_grid_ao_opacity.msg" ":defaultTextureList1.tx" -na;
// End of multi_uv_simple.ma
