#!/bin/bash

export PXR_WORK_THREAD_LIMIT=-3
export AL_USDMAYA_LOCATION=$1
export PXR_PLUGINPATH_NAME=$AL_USDMAYA_LOCATION/lib/usd:$PXR_PLUGINPATH_NAME
export LD_LIBRARY_PATH=$MAYA_LOCATION/lib:$AL_USDMAYA_LOCATION/lib:$LD_LIBRARY_PATH
export PATH=$MAYA_LOCATION/bin:$PATH
export MAYA_PLUG_IN_PATH=$AL_USDMAYA_LOCATION/plugin:$MAYA_PLUG_IN_PATH
export PYTHONPATH=$1/lib/python:$PYTHONPATH

maya -batch -script "$3/run_mayaplugin_tests.mel"
