#ifndef __HDMAYA_AL_DEBUG_CODES_H__
#define __HDMAYA_AL_DEBUG_CODES_H__

#include <pxr/pxr.h>
#include <pxr/base/tf/debug.h>

PXR_NAMESPACE_OPEN_SCOPE

TF_DEBUG_CODES(
	HDMAYA_AL_CALLBACKS,
    HDMAYA_AL_PLUGIN,
    HDMAYA_AL_POPULATE,
    HDMAYA_AL_SELECTION
);

PXR_NAMESPACE_CLOSE_SCOPE

#endif // __HDMAYA_AL_DEBUG_CODES_H__
