# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the specified branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    # The type of runners that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - run: mkdir -p artifacts

    - run: echo hello > artifacts/world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: world-artifact
        path: artifacts/world.txt

    # Launch workflow for build and test
    - name: Launch CI to build and test
      shell: bash
      run: sleep 60s
